### ISSUE TITLE
Kernel dies when running plot_partial_dependence

### ISSUE THREAD

**Issue by alay18** [datascienceinc/Skater#212] opened 2018-03-26 09:32 UTC
Hello, 

I'm currently having trouble running plot_partial_dependence for my XGBoost model. 

My kernel dies when I try to run the script, and this happens also if I run partial_dependence: 
The kernel appears to have died. It will restart automatically.

In terminal, it says: 
malloc: *** error for object 0x100007f87ba95b8c: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

There doesn't seem to be an issue when I run plot_partial_dependence for my random forest model. 

Could someone please look into this? Thanks in advance for your help!

**Comment by aikramer2** [comment] 2018-04-07 21:07
Looks like this is an issue with multiprocessing/xgboost compatibility, see https://github.com/dmlc/xgboost/issues/2163

@pramitchoudhary might be worth checking to see if changing the spawner to a forkserver will be effective. Would need to check that thats a stable spawner on the major platforms.

@alay18 in mean time, can you try setting n_jobs=1 if you're running pdp with an xgboost model?

**Comment by alay18** [comment] 2018-04-09 08:25
@aikramer2 Hey, I've tried setting n_jobs = -1 but the same thing happened. Please let me know if there's any updates on your side.

**Comment by aikramer2** [comment] 2018-04-09 16:08
@alay18 try n_jobs=1, not -1. n_jobs=-1 will use as many processes as are available.

**Comment by alay18** [comment] 2018-04-09 16:14
@aikramer2 thanks for pointing that out, just tried n_jobs = 1, the kernel still died.

**Comment by pramitchoudhary** [comment] 2018-04-11 20:59
thanks, @aikramer2. @alay18 did the issue resolve when using n_jobs=1?

**Comment by alay18** [comment] 2018-04-12 11:51
@pramitchoudhary hello, unfortunately using n_jobs = 1 did not resolve the issue.

**Comment by pramitchoudhary** [comment] 2018-04-23 17:56
@alay18 will it be possible to share the code(or example snippet) for the XGBoost model that you are trying to use. Apologies for the slow response, have been beaten down with releasing new features and documentation. Let's get this resolved.

**Comment by alay18** [comment] 2018-04-24 13:25
@pramitchoudhary here it is:

#specify XGB for inner loop - grid search
xgb = XGBRegressor(objective='reg:linear', booster='gbtree', n_jobs= -1)

#XGB parameters for grid search
xgb_grid = {"max_depth" : [6], 
          "learning_rate" : [0.2], 
          "gamma" : [0], 
          "n_estimators" : [150], 
          "min_child_weight" : [1], 
          "base_score" : [0.5], 
          "subsample" : [1], 
          "max_delta_step" : [0], 
          "colsample_bytree" : [0.5], 
          "colsample_bylevel" : [0.4], 
          "reg_alpha" : [0], 
          "reg_lambda" : [60], 
          "scale_pos_weight" : [1]
         }

clf = GridSearchCV(xgb, param_grid = xgb_grid, cv = inner_cv, n_jobs = -1)
clf.fit(X, y)
nested_score = cross_validate(clf, X, y, cv=outer_cv, n_jobs= -1, scoring = ('r2', 'neg_mean_squared_error'))
nested_scores_mean = nested_score['test_r2'].mean()
nested_rmse_mean = (np.sqrt(-nested_score['test_neg_mean_squared_error'])).mean()
print (nested_scores_mean)
print (nested_rmse_mean)

#Skater feature importance
skater_model = InMemoryModel(clf.predict, examples = X)
interpreter = Interpretation()
interpreter.load_data(X)
pdp = interpreter.partial_dependence.plot_partial_dependence(
    feature_ids = ['marksandspencer'], modelinstance = skater_model, grid_resolution = 30, n_jobs = 1)
plt.show()

**Comment by pramitchoudhary** [comment] 2018-04-25 15:42
@aikramer2 will you have time to take a look at this and see if we can resolve it or is it something that we would need help from the XGBoost guys?

**Comment by pramitchoudhary** [comment] 2018-05-16 21:06
@aikramer2 Did you get a chance to take a look at this issue?

**Comment by pramitchoudhary** [comment] 2018-06-16 17:35
looking into this, apologies for all the delays.

**Comment by pramitchoudhary** [comment] 2018-06-17 07:55
@alay18 @aikramer2 alright still a little blind on how XgBosst is handling concurrency in-terms of splitting the trees internally but there seems to be some reported issues in the way XgBoost handles thread pool internally and python's multiprocessing libraries. For more information checkout the [FAQ](http://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux). The link that @aikramer2 had referenced earlier contains good history on this thread. Also, you might also get a dead kernel issue with `XGBoost` and `cross_validate`(I was not able to get it working).

Now, to get this working with a workaround, the below mentioned code worked for me,

%matplotlib inline
import matplotlib.pyplot
from sklearn.datasets import load_boston, load_breast_cancer
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression

import matplotlib.pyplot as plt
#### Reference for customizing matplotlib: https://matplotlib.org/users/style_sheets.html
plt.style.use('ggplot')
import pandas as pd
import numpy as np

# Load Bosting housing data
regressor_data = load_boston()
# Get information about the data
print(regressor_data.DESCR)

from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate
# XGRegressor example
xgb = XGBRegressor(objective='reg:linear', booster='gbtree', n_jobs= -1)

#XGB parameters for grid search
xgb_grid = {"max_depth" : [6],
"learning_rate" : [0.2],
"gamma" : [0],
"n_estimators" : [150],
"min_child_weight" : [1],
"base_score" : [0.5],
"subsample" : [1],
"max_delta_step" : [0],
"colsample_bytree" : [0.5],
"colsample_bylevel" : [0.4],
"reg_alpha" : [0],
"reg_lambda" : [60],
"scale_pos_weight" : [1]
}

clf = GridSearchCV(xgb, param_grid = xgb_grid, cv = 3, n_jobs = -1)
clf.fit(regressor_X, regressor_y)

# Model Evaluation 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

y_hat = clf.predict(regressor_X)
print(mean_squared_error(regressor_y, y_hat))
print(r2_score(regressor_y, y_hat))

# Model Inference
from skater.core.explanations import Interpretation
interpreter = Interpretation(regressor_X, feature_names=regressor_data.feature_names)
from skater.model import InMemoryModel
annotated_model = InMemoryModel(clf.predict, examples=regressor_X)
print("Number of classes: {}".format(annotated_model.n_classes))
print("Input shape: {}".format(annotated_model.input_shape))
print("Model Type: {}".format(annotated_model.model_type))
print("Output Shape: {}".format(annotated_model.output_shape))
print("Output Type: {}".format(annotated_model.output_type))
print("Returns Probabilities: {}".format(annotated_model.probability))

print("2-way partial dependence plots")
# Features can passed as a tuple for 2-way partial plot
pdp_features = [('DIS', 'RM')]
interpreter.partial_dependence.plot_partial_dependence(
    pdp_features, annotated_model, grid_resolution=30, n_jobs=1
)

print("1-way partial dependence plots")
# or as independent features for 1-way partial plots
pdp_features = ['DIS', 'RM']
interpreter.partial_dependence.plot_partial_dependence(
pdp_features, annotated_model, grid_resolution=30, progressbar=False, n_jobs=1, with_variance=True
)

Will add as an example notebook as well, so that its easier for other folks.

**Comment by pramitchoudhary** [comment] 2018-06-17 09:30
@alay18  Added a notebook example [here](https://github.com/datascienceinc/Skater/blob/master/examples/xgboost_regression_example.ipynb)
Marking this issue as resolved. For a better solution, will open a different ticket focusing on resolving the thread pool handling. Feel free to reopen the issue if things still dont work on your end.

**Closed** 2018-06-17 09:30 UTC
Labels: bug, question

**Comment by jschular** [comment] 2019-03-14 01:37
I'm still having this issue on some notebooks

**Comment by jschular** [comment] 2019-03-14 01:51
> @alay18 Added a notebook example [here](https://github.com/datascienceinc/Skater/blob/master/examples/xgboost_regression_example.ipynb)
> Marking this issue as resolved. For a better solution, will open a different ticket focusing on resolving the thread pool handling. Feel free to reopen the issue if things still dont work on your end.

FYI this kills the kernel

**Comment by zoj613** [comment] 2019-10-25 08:34
I have this issue too when using xgboost.sklearn API. It never shows anything when I try to generate plots inside a notebook
